export const WS_PROFILE_ORDERS_CONNECT = "WS_PROFILE_ORDERS_CONNECT";
export const WS_PROFILE_ORDERS_DISCONNECT = "WS_PROFILE_ORDERS_DISCONNECT";
export const WS_PROFILE_ORDERS_CONNECTING = "WS_PROFILE_ORDERS_CONNECTING";
export const WS_PROFILE_ORDERS_OPEN = "WS_PROFILE_ORDERS_OPEN";
export const WS_PROFILE_ORDERS_CLOSE = "WS_PROFILE_ORDERS_CLOSE";
export const WS_PROFILE_ORDERS_MESSAGE = "WS_PROFILE_ORDERS_MESSAGE";
export const WS_PROFILE_ORDERS_ERROR = "WS_PROFILE_ORDERS_ERROR";

export const wsProfileOrdersConnect = (url) => ({
  type: WS_PROFILE_ORDERS_CONNECT,
  payload: url,
});

export const wsProfileOrdersDisconnect = () => ({
  type: WS_PROFILE_ORDERS_DISCONNECT,
});